### ISSUE TITLE
Coins with prices < 0 USD

### ISSUE THREAD

**Issue by arcanecfg** [8go/coinbash#1]
The prices of the coins that have values < 0 are displayed as 0. The prices would be better with a few decimal places. Same for the price in Bitcoin.

Thanks for taking the time to make this btw.
![image](https://user-images.githubusercontent.com/19188170/43343852-6d430424-9205-11e8-9960-c0fb345f1a28.png)

**Comment by abdullasharapov** [comment]
Hi! What about coins with values < 0?

**Comment by 8go** [comment]
It is the way it is for simplicity.
To get digits after the comma, just change the occurrence of `7.f` with `7.2f` in the script.
Voila, you have cents.
