### ISSUE TITLE
Simplify output for only getting the price

### ISSUE THREAD

**Issue by Jzarecta** [8go/coinbash#2]
This would be to integrate into larger scripts where it only returns the price of the selected crypto. 
``` 
<command> -s btc
<price>
```
And have something like:

```
foo = $(<command> -s btc)
echo $foo
<price>
```

**Comment by 8go** [comment]
@Jzarecta 

You can do so by using a `head` or `tail` and then `cut` to get the field you desire. 

To get teh BTC price, you would do:

`coinbash.sh -i bitcoin | head -n 2 | tail -n 1 | tr -s " " | cut -d " " -f 4`
