### ISSUE TITLE
API change could U update?

### ISSUE THREAD

**Issue by trzesicki** [8go/coinbash#3]
./coinbash.sh
jq: error (at <stdin>:0): Cannot index object with number

**Comment by ghost** [comment]
in the meantime while this is fixed you might want to have a look at my repo for similar functionality  https://github.com/mountaineerbr/markets

**Comment by 8go** [comment]
@trzesicki 

I updated to the latest API version. It is working again, but Coinmarketcap now requires an API key.

You can get such an API key for free from the coinmarketcap.com website.

**Comment by 8go** [comment]
Thanks @mountaineerbr  for chiming in and providing your helpful link. Appreciated.
I update my version today. So, it is working again ...
