### ISSUE TITLE
coinbash.sh getting incorrect ETH price

### ISSUE THREAD

**Issue by knorr-goose** [8go/coinbash#4]
HI !!  I am using ./coinbash.sh -l eth,btc,bnb,cake,dai and I get incorrect ETH price:
Rank  Symbol  Name          USD              24h-Change  7d-Change  Market-cap-USD
1     BTC     Bitcoin       57.334,71455242  +0,2%       +2,5%      1.072.302.842.925
2     ETH     Ethereum      3.802,50834040   +8,4%       +38,8%     440.241.270.615
3     BNB     Binance-Coin  634,98641753     -1,0%       +5,4%      97.427.805.597
29    CAKE    PancakeSwap   37,23198535      -0,4%       -7,2%      6.073.360.461
42    DAI     Dai           1,00359462       +0,3%       +0,3%      4.531.673.786
Market data source: https://www.coinmarketcap.com on vie 07 may 2021 12:01:33 -03
Do you have any notice of a possible bug/incorrout ??

**Comment by 8go** [comment]
Thanks @knorr-goose for commenting.

This is very unusual, very strange. 

The argument "eth" is just passed into the coinmarketcap API. There is no processing in the script. So, I cannot really see how there could be something wrong in the script specific to ETH.

How did you determine that the price is wrong? Did you compare it to coinmarketcap web site in real-time?
Comparing price to other price sources is not valid as different price feeds will definitely have different prices.
