### ISSUE TITLE
Unexpected "("

### ISSUE THREAD

**Issue by mittelbach** [8go/coinbash#6]
When I call the script, I received:  coinbash.sh: 175: Syntax error: "(" unexpected

**Comment by ptmplop** [comment]
run it with bash not sh

**Comment by 8go** [comment]
@mittelbach try the new version. Try running it with bash, preferably with GNU bash, version 5.1 or higher.

Thanks @ptmplop with helping out and chiming in.

Closing issue because I cannot reproduce it.
